import Foundation
import SwiftData

@Model
final class Caption {
    var text: String
    var isAutoGenerated: Bool = true
    var generatedDate: Date = Date()
    var editedDate: Date?

    @Relationship(deleteRule: .nullify)
    var memory: Memory?

    init(text: String, isAutoGenerated: Bool = true) {
        self.text = text
        self.isAutoGenerated = isAutoGenerated
    }
}
