import Foundation
import SwiftData

@Model
final class Category {
    @Attribute(.unique) var name: String
    var isAutoGenerated: Bool = true
    var localizedName: String?

    @Relationship(deleteRule: .nullify)
    var photos: [Photo] = []

    @Relationship(deleteRule: .nullify, inverse: \Category.parentCategory)
    var subcategories: [Category] = []

    @Relationship(deleteRule: .nullify)
    var parentCategory: Category?

    init(name: String, isAutoGenerated: Bool = true) {
        self.name = name
        self.isAutoGenerated = isAutoGenerated
    }
}
