import Testing
import SwiftData
@testable import MemoryKeeper

@Suite("Memory Model Tests")
struct MemoryTests {

    @Test("Memory stores type correctly")
    func memoryType() throws {
        let config = ModelConfiguration(isStoredInMemoryOnly: true)
        let container = try ModelContainer(
            for: Photo.self, Category.self, DuplicateGroup.self, Memory.self, Caption.self,
            configurations: config
        )
        let context = ModelContext(container)

        let onThisDay = Memory(type: .onThisDay)
        let forgotten = Memory(type: .forgotten)

        context.insert(onThisDay)
        context.insert(forgotten)
        try context.save()

        let fetched = try context.fetch(FetchDescriptor<Memory>())
        #expect(fetched.count == 2)
        #expect(fetched.contains { $0.type == .onThisDay })
        #expect(fetched.contains { $0.type == .forgotten })
    }

    @Test("Memory links to photos")
    func memoryPhotosRelationship() throws {
        let config = ModelConfiguration(isStoredInMemoryOnly: true)
        let container = try ModelContainer(
            for: Photo.self, Category.self, DuplicateGroup.self, Memory.self, Caption.self,
            configurations: config
        )
        let context = ModelContext(container)

        let memory = Memory(type: .onThisDay)
        let photo1 = Photo(assetIdentifier: "memory-photo-1")
        let photo2 = Photo(assetIdentifier: "memory-photo-2")

        memory.photos = [photo1, photo2]
        context.insert(memory)
        try context.save()

        let fetched = try context.fetch(FetchDescriptor<Memory>())
        #expect(fetched.first?.photos.count == 2)
    }

    @Test("Memory has caption relationship")
    func memoryCaptionRelationship() throws {
        let config = ModelConfiguration(isStoredInMemoryOnly: true)
        let container = try ModelContainer(
            for: Photo.self, Category.self, DuplicateGroup.self, Memory.self, Caption.self,
            configurations: config
        )
        let context = ModelContext(container)

        let memory = Memory(type: .forgotten)
        let caption = Caption(text: "A beautiful day in 2020", isAutoGenerated: true)
        memory.caption = caption

        context.insert(memory)
        try context.save()

        let fetched = try context.fetch(FetchDescriptor<Memory>())
        #expect(fetched.first?.caption?.text == "A beautiful day in 2020")
        #expect(fetched.first?.caption?.isAutoGenerated == true)
    }
}
